** If there's magic in boxing, it's the magic of fighting battles beyond endurance, beyond cracked ribs, ruptured kidneys and detached retinas. It's the magic of risking everything for a dream that nobody sees but you.

** Frankie likes to say that boxing is an unnatural act, that everything in boxing is backwards: sometimes the best way to deliver a punch is to step back... But step back too far and you ain't fighting at all.

** I'm 32, Mr. Dunn, and I'm here celebrating the fact that I spent another year scraping dishes and waitressing which is what I've been doing since 13, and according to you I'll be 37 before I can even throw a decent punch, which I have to admit, after working on this speed bag for a month may be the God's simple truth. Other truth is, my brother's in prison, my sister cheats on welfare by pretending one of her babies is still alive, my daddy's dead, and my momma weighs 312lbs. If I was thinking straight I'd go back home, find a used trailer, buy a deep fryer and some oreos. Problem is, this the only thing I ever felt good doing. If I'm too old for this then I got nothing. That enough truth to suit you?

** There is magic in fighting battles beyond endurance.

** To make a fighter you gotta strip them down to bare wood: you can't just tell 'em to forget everything you know if you gotta make 'em forget even their bones... make 'em so tired they only listen to you, only hear your voice, only do what you say and nothing else... show 'em how to keep their balance and take it away from the other guy... how to generate momentum off their right toe and how to flex your knees when you fire a jab... how to fight backing up so that the other guy doesn't want to come after you. Then you gotta show 'em all over again. Over and over and over... till they think they're born that way.
