
countries = {
"Afghanistan" : "AFN",
"Albania" : "ALL", 
"Algeria" : "DZD", 
"Angola" : "AOA", 
"Anguilla" : "XCD", 
"Antigua and Barbuda" : "XCD",
"Argentina" : "ARS", 
"Armenia" : "AMD", 
"Aruba" : "AWG", 
"Australia" : "AUD", 
"Austria" : "EUR", 
"Azerbaijan" : "AZN ",
"Bahamas" : "BSD", 
"Bahrain" : "BHD",
"Bangladesh" : "BDT",
"Barbados" : "BBD",
"Belarus" : "BYR",
"Belgium" : "EUR",
"Belize" : "BZD",
"Benin" : "XOF",
"Bermuda" : "BMD",
"Bhutan" : "BTN",
"Bolivia" : "BOB",
"Bosnia-Herzegovina" : "BAM",
"Botswana" : "BWP",
"Brazil" : "BRL",
"Brunei" : "BND",
"Bulgaria" : "BGN",
"Burkina Faso" : "XOF",
"Burundi" : "BIF",
"Cambodia" : "KHR",
"Cameroon" : "XAF",
"Canada" : "CAD",
"Cape Verde" : "CVE",
"Cayman Islands" : "KYD",
"Central African Republic" : "XAF",
"Chad" : "XAF",
"Chile" : "CLP",
"China" : "CNY",
"Colombia" : "COP",
"Comoros" : "KMF",
"Congo" : "XAF",
"Congo, Democratic Republic" : "CDF",
"Costa Rica" : "CRC",
"Croatia" : "HRK",
"Cuba" : "CUC",
"Cyprus" : "EUR",
"Czech Republic" : "CZK",
"Denmark" : "DKK",
"Djibouti" : "DJF",
"Dominica" : "XCD",
"Dominican Republic" : "DOP",
"Egypt" : "EGP",
"Equatorial Guinea" : "GQE",
"Eritrea" : "ERN",
"Estonia" : "EEK",
"Ethiopia" : "ETB",
"Falkland Islands" : "FKP",
"Fiji" : "FJD",
"Finland" : "EUR",
"France" : "EUR",
"French Polynesia" : "XPF",
"Gabon" : "XAF",
"Gambia" : "GMD",
"Georgia" : "GEL",
"Germany" : "EUR",
"Ghana" : "GHS",
"Gibraltar" : "GIP",
"Greece" : "EUR",
"Grenada" : "XCD",
"Guatemala" : "GTQ",
"Guinea-Bissau" : "XOF",
"Guinea" : "GNF",
"Guyana" : "GYD",
"Haiti" : "HTG",
"Honduras" : "HNL",
"Hong Kong" : "HKD",
"Hungary" : "HUF",
"Iceland" : "ISK",
"India" : "INR",
"Indonesia" : "IDR",
"International Monetary Fund" : "XDR",
"Iran" : "IRR",
"Iraq" : "IQD",
"Ireland" : "EUR",
"Israel" : "ILS",
"Italy" : "EUR",
"Jamaica" : "JMD",
"Japan" : "JPY",
"Jordan" : "JOD",
"Kazakhstan" : "KZT",
"Kenya" : "KES",
"Korea, North " : "KPW",
"Korea, South " : "KRW",
"Kuwait" : "KWD",
"Kyrgyzstan" : "KGS",
"Laos" : "LAK",
"Latvia" : "LVL",
"Lebanon" : "LBP",
"Lesotho" : "LSL",
"Liberia" : "LRD",
"Libya" : "LYD",
"Lithuania" : "LTL",
"Luxembourg" : "EUR",
"Macau" : "MOP",
"Macedonia (Former Yug. Rep.)" : "MKD",
"Madagascar" : "MGA",
"Malawi" : "MWK",
"Malaysia" : "MYR",
"Maldives" : "MVR",
"Mali" : "XOF",
"Malta" : "EUR",
"Mauritania" : "MRO",
"Mauritius" : "MUR",
"Mexico" : "MXN",
"Moldova" : "MDL",
"Mongolia" : "MNT",
"Montserrat" : "XCD",
"Morocco" : "MAD",
"Mozambique" : "MZM",
"Myanmar" : "MMK",
"Namibia" : "NAD",
"Nepal" : "NPR",
"Netherlands Antilles" : "ANG",
"Netherlands" : "EUR",
"New Caledonia" : "XPF",
"New Zealand" : "NZD",
"Nicaragua" : "NIO",
"Niger" : "XOF",
"Nigeria" : "NGN",
"Norway" : "NOK",
"Oman" : "OMR",
"Pakistan" : "PKR",
"Panama" : "PAB",
"Papua New Guinea" : "PGK",
"Paraguay" : "PYG",
"Peru" : "PEN",
"Philippines" : "PHP",
"Poland" : "PLN",
"Portugal" : "EUR",
"Qatar" : "QAR",
"Romania" : "RON",
"Russia" : "RUB",
"Rwanda" : "RWF",
"Saudi Arabia" : "SAR",
"Serbia" : "RSD",
"Seychelles" : "SCR",
"Sierra Leone" : "SLL",
"Singapore" : "SGD",
"Slovakia" : "EUR",
"Slovenia" : "EUR",
"Solomon Islands" : "SBD",
"Somalia" : "SOS",
"South Africa" : "ZAR",
"Spain" : "EUR",
"Sri Lanka" : "LKR",
"St. Helena" : "SHP",
"St. Kitts and Nevis" : "XCD",
"St. Lucia" : "XCD",
"St. Vincent and the Grenadines" : "XCD",
"Sudan" : "SDG",
"Suriname" : "SRD",
"Swaziland" : "SZL",
"Sweden" : "SEK",
"Switzerland" : "CHF",
"Syria" : "SYP",
"Taiwan" : "TWD",
"Tajikistan" : "TJS",
"Tanzania" : "TZS",
"Thailand" : "THB",
"Togo" : "XOF",
"Trinidad and Tobago" : "TTD",
"Tunisia" : "TND",
"Turkey" : "TRY",
"Turkmenistan" : "TMT",
"Uganda" : "UGX",
"Ukraine" : "UAH",
"United Arab Emirates" : "AED",
"United Kingdom" : "GBP",
"United States of America" : "USD",
"Uruguay" : "UYU",
"Uzbekistan" : "UZS",
"Vanuatu" : "VUV",
"Venezuela" : "VEB",
"Vietnam" : "VND",
"Wallis and Futuna Islands" : "XPF",
"Western Samoa" : "WST",
"Yemen" : "YER",
"Zambia" : "ZMK",
"Zimbabwe" : "ZWR",




    }
