
countries = {
    "India": "INR",
    "United Arab Emirates" : "AED",
    "United States": "USD",
    "Switzerland": "CHF",
    "Germany": "EUR",
    "Zimbabwe": "ZWD",
    "Benin" : "XOF",
    "Uzbekistan": "UZS",
    "Indonesia" : "IDR",
    "Nepal" : "NPR",
    "China" : "CNY",
    "Russia" : "RUB",
    "Norway" : "NOK",
    "Sweden" : "SEK",
    "Pakistan" : "PKR",
    "Canada" : "CAD",
    "Australia": "AUD",
    "United Kingdom" : "GBP",
    "Argentina" : "ARS",
    "Bolivia": "BOB",
    "Brazil" : "BRL",
    "Chile" : "CLP",
    "Venezuela" : "VEF",
    "Uruguay" : "UYU",
    "Mexico" : "MXN",
    "Greenland" : "DKK",
    "New Zealand" : "NZD",
    "Italy" : "EUR",
    "France" : "EUR",
    }
